- name: install needed python package
  apt:
    name: python3-pymysql
    state: present
    update_cache: yes

- name: install mariadb-server
  apt:
    name: mariadb-server
    state: present

- name: start mariadb
  service:
    name: mariadb
    state: started

- name: set bind address
  lineinfile:
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
    line: 'bind-address = 0.0.0.0'
    state: present
    regexp: "^bind-address(.*)"
  notify: restart mariadb

- name: creates db user dba
  mysql_user:
    name: dba
    password: "g3h31m"
    login_user: root
    login_password: password
    priv: "*.*:ALL,GRANT"
    state: present
    host: "%"
    login_unix_socket: /var/run/mysqld/mysqld.sock
