# cat tasks/deploy-webapp.yml
- name: delete previous backup
  ansible.builtin.file:
    path: "{{ tomcat_app_base }}/{{ webapp_target_name }}.war.previous"
    state: absent

- name: create new backup
  ansible.builtin.command: mv {{ tomcat_app_base }}/{{ webapp_target_name }}.war {{ tomcat_app_base }}/{{ webapp_target_name }}.war.previous
  ignore_errors: true

- name: copy webapp {{ webapp_source_path }} to {{ webapp_target_name }}
  ansible.builtin.copy:
    src: "{{ webapp_source_path }}"
    dest: "{{ tomcat_app_base }}/{{ webapp_target_name }}.war"
    mode: "660"
