# cat tasks/start-tomcat.yml
- name: start tomcat
  ansible.builtin.service:
    name: tomcat
    enabled: yes
    state: started
  become: true

- name: wait for tomcat to start
  ansible.builtin.wait_for:
    port: 8080
    timeout: 60
