# cat tasks/stop-tomcat.yml
- name: stop tomcat
  ansible.builtin.service:
    name: tomcat
    state: stopped
  become: true

- name: wait tomcat shutdown
  ansible.builtin.wait_for:
    port: 8080
    state: stopped
    timeout: 60
