- hosts: 192.168.56.10
  become: true
  become_method: sudo
  tasks:
    - name: Ensure Python modules
      ansible.builtin.apt:
        name: python-apt

    - name: add nodejs ppa
      ansible.builtin.apt_repository:
        repo: ppa:chris-lea/node.js

    - name: install nodejs package
      ansible.builtin.apt:
        name: nodejs
