#!/bin/bash

export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-i386/
export CATALINA_HOME=/opt/tomcat

if [ "`whoami`" == "vagrant" ]; then
    exec sudo /etc/init.d/tomcat "$@"
fi

su - vagrant -c "/opt/tomcat/bin/catalina.sh $*"