- hosts: database_server
  become: yes
  vars:
    mysql_root_password: password
  tasks:
    - name: install needed python package
      apt:
        name: python3-pymysql  #['python-mysqldb', 'python-apt']
        state: present
        update_cache: yes

    - name: install mysql-server
      apt:
        name: mysql-server
        state: present

    - name: start mysql
      service:
        name: mysql
        state: started

    - name: set bind address
      lineinfile:
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        line: 'bind-address = 0.0.0.0'
        state: present
        regexp: "^bind-address(.*)"
      notify: restart mysql

    - name: creates db user dba
      mysql_user:
        name: dba
        password: "g3h31m"
        login_user: root
        login_password: password
        priv: "*.*:ALL,GRANT"
        state: present
        host: "%"
        login_unix_socket: /var/run/mysqld/mysqld.sock

  handlers:
     - name: restart mysql
       service:
         name: mysql
         state: restarted
