- hosts: database_server
  become: yes
  vars:
    mariadb_root_password: password
  tasks:
    - name: install needed python package
      ansible.builtin.apt:
        name: python3-pymysql
        state: present
        update_cache: yes

    - name: install mariadb-server
      ansible.builtin.apt:
        name: mariadb-server
        state: present

    - name: start mariadb
      ansible.builtin.service:
        name: mariadb
        state: started

    - name: set bind address
      ansible.builtin.lineinfile:
        dest: /etc/mysql/mariadb.conf.d/50-server.cnf
        line: 'bind-address = 0.0.0.0'
        state: present
        regexp: "^bind-address(.*)"
      notify: restart mariadb

    - name: creates db user dba
      ansible.builtin.mysql_user:
        name: dba
        password: "g3h31m"
        login_user: root
        login_password: password
        priv: "*.*:ALL,GRANT"
        state: present
        host: "%"
        login_unix_socket: /var/run/mysqld/mysqld.sock

  handlers:
     - name: restart mariadb
       ansible.builtin.service:
         name: mariadb
         state: restarted
